name: Deploy Hugo to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Install Hugo Modules
      run: hugo mod get

    - name: Build Hugo Site
      run: hugo --minify

    - name: Install Azure SWA CLI
      run: npm install -g @azure/static-web-apps-cli

    - name: Deploy to Azure Static Web App using CLI
      run: |
        swa deploy ./public --app-name learndsc -d $AZURE_STATIC_WEB_APPS_API_TOKEN  --env production
      env:
        AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}